### ISSUE TITLE
Clases Entidades (1ra Parte)

### ISSUE THREAD

**Issue by mehs2690** [CursoMvc/PuntoVentaMvc#1]
#Terminar las clases Entidades

se deben de terminar las clases entidades en el proyecto PvEntidades, con la normalización de código C#, y debe de estar bien documentado cada clase

**Comment by davidhsan** [comment]
He documentado las clases faltantes y complementado una de ellas que por lo que vi es la única que faltaba en sus propiedades.

Saludos.
